export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const LOCATION_REPOSITORY = 'LOCATION_REPOSITORY';
export const OFFER_REPOSITORY = 'OFFER_REPOSITORY';
export const SOURCE_REPOSITORY = 'SOURCE_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
